<?php
/**
 * Created by PhpStorm.
 * User: Admin
 * Date: 08.09.2018
 * Time: 17:43
 */

namespace shop\entities\Shop;


use paulzi\nestedsets\NestedSetsBehavior;
use shop\entities\behaviors\MetaBehavior;
use shop\entities\Shop\queries\CategoryQuery;
use yii\db\ActiveRecord;

/**
 * Class Category
 *
 * @package shop\entities\Shop
 * @property integer $id
 * @property string $name
 * @property string $slug
 * @property string $title
 * @property string $description
 *
 * @property Category $parent
 * @property Meta $meta
 *
 * @mixin NestedSetsBehavior
 *
 */
class Category extends ActiveRecord
{
    public $meta;

    public static function create($name, $slug, $title, $description, Meta $meta): self
    {
        $category = new static();
        $category->name = $name;
        $category->slug = $slug;
        $category->title = $title;
        $category->description = $description;
        $category->meta = $meta;

        return $category;
    }

    public  function edit($name, $slug, $title, $description, Meta $meta): self
    {
        $this->name = $name;
        $this->slug = $slug;
        $this->title = $title;
        $this->description = $description;
        $this->meta = $meta;
    }

    public function behaviors()
    {
        return [
            MetaBehavior::className(),
            NestedSetsBehavior::className()
        ];
    }

    public function transactions()
    {
        return [
            self::SCENARIO_DEFAULT => self::OP_ALL,
        ];
    }

    public static function find()
    {
        return new CategoryQuery(get_called_class());
    }

    public static function tableName()
    {
        return '{{%shop_categories}}'; // TODO: Change the autogenerated stub
    }
}